[package]
name = "opi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.20"

[[bin]]
name = "opi-tui"
path = "src/opi-tui.rs"